import { config as loadDotenv } from 'dotenv';
import fs from 'node:fs';
import path from 'node:path';

import { ENV_FILE } from '../src/paths.js';
loadDotenv({ path: ENV_FILE });

import { createBaseTemplate } from '../src/engine/bootstrap.js';
import {
  getTemplatePaths,
  loadMetadata,
  templateExists,
} from '../src/storage/templateManager.js';

const TEMPLATE_ID = 'smoketest-instagram-square';

async function main(): Promise<void> {
  if (templateExists(TEMPLATE_ID)) {
    const { dir } = getTemplatePaths(TEMPLATE_ID);
    fs.rmSync(dir, { recursive: true, force: true });
    process.stderr.write(`[smoketest] Removed previous template: ${dir}\n`);
  }

  process.stderr.write('[smoketest] Creating base template ...\n');
  await createBaseTemplate({
    templateId: TEMPLATE_ID,
    name: 'Smoketest Instagram Square',
    description: 'Generated by the smoketest script to validate the bootstrap.',
    platform: 'instagram_square',
    variables: ['headline', 'postText'],
  });

  const { zip, meta, fileUrl } = getTemplatePaths(TEMPLATE_ID);
  const stats = fs.statSync(zip);
  const metadata = loadMetadata(TEMPLATE_ID);

  process.stderr.write('\n[smoketest] Success.\n');
  process.stderr.write(`  Template ID:   ${metadata.id}\n`);
  process.stderr.write(`  Platform:      ${metadata.platform}\n`);
  process.stderr.write(
    `  Dimensions:    ${metadata.dimensions.width}x${metadata.dimensions.height}\n`,
  );
  process.stderr.write(`  Variables:     ${metadata.variables.join(', ')}\n`);
  process.stderr.write(`  Placeholders:  ${metadata.placeholders.join(', ')}\n`);
  process.stderr.write(`  Archive size:  ${stats.size} bytes\n`);
  process.stderr.write(`  Archive path:  ${zip}\n`);
  process.stderr.write(`  Archive URL:   ${fileUrl}\n`);
  process.stderr.write(`  Metadata:      ${meta}\n`);

  // Sanity check: ZIP signature 'PK\x03\x04'
  const head = fs.readFileSync(zip).subarray(0, 4);
  const looksLikeZip =
    head[0] === 0x50 && head[1] === 0x4b && head[2] === 0x03 && head[3] === 0x04;
  if (!looksLikeZip) {
    throw new Error('Archive has no ZIP signature — likely corrupted.');
  }
  process.stderr.write('  ZIP signature: OK\n');

  process.stderr.write(
    `\n[smoketest] Tip: inspect the archive with:\n  unzip -l ${path.relative(process.cwd(), zip)}\n`,
  );
}

main().catch((err) => {
  process.stderr.write(`\n[smoketest] Error: ${err instanceof Error ? err.message : String(err)}\n`);
  if (err instanceof Error && err.stack) {
    process.stderr.write(err.stack + '\n');
  }
  process.exit(1);
});
